### ISSUE TITLE
Standardize version updates

### ISSUE THREAD

**Issue by smikeblog** [doronbehar/pistol#14]
env GO111MODULE=on go get -u github.com/doronbehar/pistol/cmd/pistol
go: found github.com/doronbehar/pistol/cmd/pistol in github.com/doronbehar/pistol v0.0.4
go: github.com/klauspost/pgzip upgrade => v1.2.3
go: github.com/galdor/go-cmdline upgrade => v1.1.1
go: github.com/adrg/xdg upgrade => v0.2.1
go: github.com/klauspost/compress upgrade => v1.10.4
go: github.com/dlclark/regexp2 upgrade => v1.2.0
go: github.com/sirupsen/logrus upgrade => v1.5.0
go: golang.org/x/sys upgrade => v0.0.0-20200409092240-59c9f1ba88fa
go: github.com/konsorten/go-windows-terminal-sequences upgrade => v1.0.2
go: github.com/andybalholm/brotli upgrade => v1.0.0
go: github.com/pierrec/lz4 upgrade => v2.5.0+incompatible
go: github.com/golang/snappy upgrade => v0.0.1
go: github.com/nwaples/rardecode upgrade => v1.1.0
go: github.com/ulikunitz/xz upgrade => v0.5.7

and 
~/C/g/bin ❯❯❯  $GOBIN/pistol --version
v0.0.3 (2019-12-13)

**Comment by doronbehar** [comment]
You _are_ probably using the latest version, I'm just a fool that I haven't updated:

https://github.com/doronbehar/pistol/blob/35bc7581f9501a0a9f73c74195dcb1d684f1eead/cmd/pistol/main.go#L25

I'm waiting for some feedback regarding #13 and once it'll merge I'll release 0.0.5 with that line updated. Thanks for notifying me.

**Comment by doronbehar** [comment]
FYI v0.0.5 is out.

**Comment by doronbehar** [comment]
Closed in #17 .
