### ISSUE TITLE
pistol panics when pistol.conf is empty

### ISSUE THREAD

**Issue by kpatel28** [doronbehar/pistol#3]
Hey I noticed that when pistol.conf is empty with only whitespace pistol panics. It appears to be a out of bounds error on line 66 of previewer.go because of the splitting on spaces.

I don't know any Go, but I guess you could strip the leading and trailing space before the string splitting if you care to fix this:

On Line 60: `def := strings.Split(strings.TrimSpace(scanner.Text()), " ")`

**Comment by doronbehar** [comment]
Thanks for reporting that! Fixed in https://github.com/doronbehar/pistol/commit/0ba1763f068b046c2380f1eba329e48d69cd65bb .
