### ISSUE TITLE
pistol.conf could be better

### ISSUE THREAD

**Issue by lucas-mior** [doronbehar/pistol#31]
I noticed that parsing of ```pistol.conf``` fails when there is more than one space between the mime type and preview program.
Which makes the config file really messy.

**Comment by doronbehar** [comment]
Could you give please a concrete example?

**Comment by lucas-mior** [comment]
``` inode/directory ls -1A --color %pistol-filename% ``` <-- works
``` inode/directory  ls -1A --color %pistol-filename% ``` <-- doesn't (I wish it did)
So that I can't align the mime types / programs properly, making the config file confusing.
It also makes it easy for errors to happen just because of one extra space character.

**Comment by doronbehar** [comment]
Thanks for catching that, I improved the config file's parsing, and I hope that works for you. A new release is available.

**Comment by lucas-mior** [comment]
Indeed, it works now, but I also noticed that empty lines (previously ignored) now break the config parsing.
Not a problem for me, but might break someone else's config.

**Comment by doronbehar** [comment]
It should work now.

https://www.reddit.com/r/ProgrammerHumor/comments/hp9wwp/biggest_lie/

**Comment by lucas-mior** [comment]
It does, thanks.
