### ISSUE TITLE
Don't exit with code 141 if stdout is terminated

### ISSUE THREAD

**Issue by lucas-mior** [doronbehar/pistol#33]
I tried to use pistol in lfp (https://gitlab.com/Provessor/lfp/) but a small problem happened,
which has to do with exit codes.
If you want to know about it, check https://gitlab.com/Provessor/lfp/-/issues/16

**Comment by doronbehar** [comment]
I'm having a hard time reproducing - `pistol large-file.txt | head -1` doesn't exit with a non-zero code for me... With `ctrl-c` it doesn't work for me either since my new laptop is too fast.

**Comment by lucas-mior** [comment]
I don't need to use `lfp` any longer, so if this isn't of interest to anyone else, I will just close this.
