### ISSUE TITLE
pistol.conf isn't loaded on OS X

### ISSUE THREAD

**Issue by duganchen** [doronbehar/pistol#36]
I'm wondering if this is the issue behind this one:

https://github.com/doronbehar/pistol/issues/19

I've noticed that on OS X, ~/.config/pistol/pistol.conf isn't loaded.

I have the following in ~/.config/pistol/pistol.conf:

    image/* viu %pistol-filename%

If I just run pistol against a image, the setting doesn't take effect:

    ▶ pistol Lohse-3840x2160.jpg
    JPEG image data, Exif standard: [TIFF image data, little-endian, direntries=0], baseline, precision 8, 3840x2160, components 3

(That's Divinity: Original Sin 2 wallpaper, if you're wondering).

But if I force it to load pistol.conf, 

    ▶ pistol -c ~/.config/pistol/pistol.conf Lohse-3840x2160.jpg

Then I see the image in the terminal.

**Comment by doronbehar** [comment]
What does `pistol --help` says on OS X?

**Comment by duganchen** [comment]
```
❯ pistol --help
Usage: /Users/dugan/go/bin/pistol OPTIONS [<file> ...]

OPTIONS

-V, --version               Print version date and exit
-c, --config <config file>  configuration file to use (defaults to ~/.config/pistol/pistol.conf)
-h, --help                  print help and exit

ARGUMENTS

file                        the file to preview
```

**Comment by duganchen** [comment]
I'm not sure why you asked that, as the path in "pistol --help" is hardcoded. I know what's wrong though.

adrg/xdg simply doesn't recognize ~/.config as a user configuration directory on OS X. It only recognizes (and searches) ~/Library/Preferences.

**Comment by doronbehar** [comment]
You are right, that path was indeed hardcoded. Now it is not, and `--help` reflects the real paths that are supposed to be used. Thanks for the report.

BTW is this surprising to you as an OS X user to use a program with such an XDG assumption? Because other golang xdg implementations use the same path for OS x - https://github.com/kyoh86/xdg & https://github.com/OpenPeeDeeP/xdg .

**Comment by duganchen** [comment]
I'd certainly say that that resolves it. 👍 

As for whether the correct OS X XDG path surprises me: I mainly have a Linux background and I'm the wrong OS X user to ask.

**Comment by luisdavim** [comment]
Can you also update the readme?

**Comment by doronbehar** [comment]
> Can you also update the readme?

Yes :) Thanks.

**Comment by luisdavim** [comment]
BTW, I've been using macOS for some time now and this was a surprise to me, most apps I use store their config in `~/.config/` I've also noticed that `helm` started using the `~/Library/` path after v3 maybe this came with some more recent version of macOS or only now developers are starting to adopt it...
