### ISSUE TITLE
Bump Chroma

### ISSUE THREAD

**Issue by meck** [doronbehar/pistol#63]
There is some new styles in `chroma 0.9.1` I would like to use. Also a release with #59 would be nice (with an associated  `nixpkgs` bump I could remove a lot of overlays). :bow:

**Comment by doronbehar** [comment]
Thanks for asking :) https://github.com/doronbehar/pistol/releases/tag/v0.2.0 .

**Comment by doronbehar** [comment]
Will close once nixpkgs version bump is merged.

**Comment by doronbehar** [comment]
https://github.com/NixOS/nixpkgs/pull/122165
