### ISSUE TITLE
man page

### ISSUE THREAD

**Issue by lucas-mior** [doronbehar/pistol#64]
If you have interest, I could write a man page for pistol.

**Comment by doronbehar** [comment]
I am interested! It's a good idea, though most of the program is already documented in the README which is an asciidoc document, that should be easily be converted to a manpage format for packagers to include. I have a few small enhancements to give to it so this should be ready on the next release.

**Comment by doronbehar** [comment]
https://github.com/doronbehar/pistol/releases/tag/v0.2.1

**Comment by doronbehar** [comment]
https://github.com/doronbehar/pistol/commit/0efe2419c355cc42f45ed6ce38dbc8bf6453889a
