### ISSUE TITLE
configuration file path doesn't corespond to README

### ISSUE THREAD

**Issue by asmarcz** [doronbehar/pistol#7]
In the README is a statement that pistol reads configuration from this path:  `~/.config/pistol/pistol.conf`

However what it actually reads is `~/.config/pistol.conf` to be easily demonstrated:
```
asmar:~/go/bin$ strace ./pistol ~/Documents/Daily.pdf 2>&1 | grep conf
newfstatat(AT_FDCWD, "/home/asmar/.config/pistol.conf", 0xc00013a9f8, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/etc/xdg/xdg-ubuntu/pistol.conf", 0xc00013aac8, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/etc/xdg/pistol.conf", 0xc00013ab98, 0) = -1 ENOENT (No such file or directory)
```

Moving from `~/.config/pistol/pistol.conf` to `~/.config/pistol.conf` works and pistol now reads configuration.

**Comment by asmarcz** [comment]
Interesting is that with cloned repository and built cmd/pistol/main.go it reads the right file.
```
asmar:~/projects/pistol/cmd/pistol$ strace ./pistol ~/Documents/Daily.pdf 2>&1 | grep conf
newfstatat(AT_FDCWD, "/home/asmar/.config/pistol/pistol.conf", {st_mode=S_IFREG|0644, st_size=67, ...}, 0) = 0
openat(AT_FDCWD, "/home/asmar/.config/pistol/pistol.conf", O_RDONLY|O_CLOEXEC) = 3
```

**Comment by asmarcz** [comment]
The same can be seen with verbose flag.
```
asmar:~$ pistol -v ~/Documents/Daily.pdf
pistol: could not find configuration file in the default location: /home/asmar/.config/pistol.conf
pistol: detected mimetype is application/pdf
PDF document, version 1.4
```

**Comment by doronbehar** [comment]
The story is that Pistol used to read `~/.config/pistol.conf` but I changed that to `~/.config/pistol/pistol.conf` for xdg consistency. Pistol is _supposed_ to read look for `~/.config/pistol/pistol.conf` first and then for `~/.config/pistol.conf`. When writing your [1st comment](https://github.com/doronbehar/pistol/issues/7#issue-534235395), did you have `~/.config/pistol/pistol.conf` exist? As expected, if it's not found, `~/.config/pistol.conf` is tested for existence.

Anyway, I'm sorry but I'm not sure what your tests have proved. The point is that both locations should be looked up for and yes - `~/.config/pistol.conf` is not documented because it's kept there for backwards compatibility. If you use only one of the locations and you can testify the configuration file isn't read at all then that's a bug.

**Comment by asmarcz** [comment]
@doronbehar 
```
asmar:~$ file .config/pistol/pistol.conf
.config/pistol/pistol.conf: ASCII text
asmar:~$ file .config/pistol.conf
.config/pistol.conf: cannot open `.config/pistol.conf' (No such file or directory)
asmar:~$ strace pistol ~/Documents/dummy.pdf 2>&1 | grep conf
newfstatat(AT_FDCWD, "/home/asmar/.config/pistol.conf", 0xc0004f6518, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/etc/xdg/xdg-ubuntu/pistol.conf", 0xc0004f65e8, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/etc/xdg/pistol.conf", 0xc0004f66b8, 0) = -1 ENOENT (No such file or directory)
asmar:~$ pistol ~/Documents/dummy.pdf
PDF document, version 1.4
asmar:~$ ln -s pistol/pistol.conf .config/pistol.conf
asmar:~$ pistol ~/Documents/dummy.pdf 
dummy pdf text
```

**Comment by doronbehar** [comment]
Sorry for a late reply. Did you put any regex for PDF files in either config files? Could you demonstrate the issue perhaps with a different program configured in either config file? To get you to my point, I just want to see the full picture, in such a demonstrating shell session as you wrote in your last comment, I want to see more then the output of `file ~/.config/pistol.conf` or whatever. Besides that, I'm not sure I understood whether `pistol` from `go get` acts differently then the one you get when installing from source.

**Comment by asmarcz** [comment]
@doronbehar I can follow up with some examples however for now (since I'm in a bus)..

The point is that pistol doesn't attempt to read `~/.config/pistol/pistol.conf` when it is installed using `go get` with the module workaround. This is demonstrated using `strace` which tracks sys calls and thus if we `grep conf` it we should get all file oriented calls for `.conf` files. When this is run with `~/.config/pistol/pistol.conf` created it shows that only `~/.config/pistol.conf` is actually checked and since it doesn't exist pistol returns general PDF info.

When we now symlink/create a file in `~/.config/pistol.conf` pistol can now read configuration and proceeds successfully.

I don't see how this could be affected by the software used to display PDF since the issue is concerning only finding the configuration file for pistol. However my `~/.config/pistol/pistol.conf` was this:

```
application/pdf pdftotext %s -
```

I'd be more than glad to provide you with as much info as necessary. However please provide exact points of what you'd want to see since I don't know what else would be needed.

**Comment by doronbehar** [comment]
Oh right so let's say I don't care what configuration file you use, I just want to make sure that `~/.config/pistol/pistol.conf` gets precedence over `~/.config/pistol.conf`. So for the sake of testing, put a different command for a regex in either of them and then run `pistol` with a file of this mime type.

Maybe something silly such as:

```
echo application/pdf echo old config reading '%s' > ~/.config/pistol.conf
echo application/pdf echo new config reading '%s' > ~/.config/pistol/pistol.conf
pistol test.pdf
```

Please also note that empty PDF files won't be suitable for the test - libmagic actually opens the files it tries to detect their mime types and reads the 'magic' characters in the files' headers so please use real world PDF files!

**Comment by asmarcz** [comment]
Ok, performed here:
```
asmar:~$ cat ~/.config/pistol.conf
application/pdf echo old config reading %s
asmar:~$ cat ~/.config/pistol/pistol.conf
application/pdf echo new config reading %s
asmar:~$ pistol ~/Documents/dummy.pdf 
old config reading /home/asmar/Documents/dummy.pdf
asmar:~$ pistol ~/Documents/Daily.pdf 
old config reading /home/asmar/Documents/Daily.pdf
```

Please note that dummy.pdf was generated with LibreOffice Writer and Daily.pdf with Google Chrome.

However I am afraid I didn't communicate properly. The problem is **not precedence**. Looking at the `strace` output in previous comments, one can easily see that `~/.config/pistol/pistol.conf` is **not attempted** to be read even when `~/.config/pistol.conf` **doesn't exist**.

**Comment by doronbehar** [comment]
I'm sorry @asmarcz but I can't reproduce. Maybe it's because I'm using the program installed straight from the git repo. I've added a `--version` / `-V` flag so it should be easier now to debug whether you have the latest version of the program installed though I would be surprised if we'll find out that `go get` doesn't fetch the latest version.

Please update Pistol and check if with `pistol -h` you see a new `--version` flag option and if the program still doesn't read the config file in the new location.

**Comment by asmarcz** [comment]
Ok, so I grabbed another computer.. Installed go and `env GO111MODULE=on go get -u github.com/doronbehar/pistol/cmd/pistol` just now. I created neither `~/.config/pistol.conf` nor `~/.config/pistol/pistol.conf`.

```
asmar@asmarHPElite:~$ strace pistol 2>&1 | grep conf
newfstatat(AT_FDCWD, "/home/asmar/.config/pistol.conf", 0xc0001cdb08, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/etc/xdg/xdg-mate/pistol.conf", 0xc0001cdbd8, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/etc/xdg/pistol.conf", 0xc0001cdca8, 0) = -1 ENOENT (No such file or directory)
asmar@asmarHPElite:~$ pistol -V
error: unknown option "V"
asmar@asmarHPElite:~$ pistol -h
Usage: pistol OPTIONS [<file> ...]

OPTIONS

-c, --config <config>  configuration file to use (defaults to /home/asmar/.config/pistol.conf)
-h, --help             print help and exit
-v, --verbosity        increase verbosity

ARGUMENTS

file                   the file to preview
```

```
asmar@asmarHPElite:~/go/bin$ ls -l --full-time 
total 9744
-rwxrwxr-x 1 asmar asmar 9974560 2019-12-13 15:58:58.836596184 +0100 pistol
asmar@asmarHPElite:~/go/bin$ cd ..
asmar@asmarHPElite:~/go$ ls -R | grep pistol
pistol
pistol
./pkg/mod/cache/download/github.com/doronbehar/pistol:
./pkg/mod/cache/download/github.com/doronbehar/pistol/@v:
pistol@v0.0.2
pistol@v0.0.2
./pkg/mod/github.com/doronbehar/pistol@v0.0.2:
./pkg/mod/github.com/doronbehar/pistol@v0.0.2/cmd:
pistol
./pkg/mod/github.com/doronbehar/pistol@v0.0.2/cmd/pistol:
./pkg/mod/github.com/doronbehar/pistol@v0.0.2/internal_writers:
```

**Comment by asmarcz** [comment]
Building yourself works as expected.
```
asmar@asmarHPElite:~/test$ git clone https://github.com/doronbehar/pistol.git
Cloning into 'pistol'...
remote: Enumerating objects: 186, done.
remote: Counting objects: 100% (186/186), done.
remote: Compressing objects: 100% (99/99), done.
remote: Total 186 (delta 95), reused 161 (delta 71), pack-reused 0
Receiving objects: 100% (186/186), 38.45 KiB | 410.00 KiB/s, done.
Resolving deltas: 100% (95/95), done.
asmar@asmarHPElite:~/test$ cd pistol/cmd/pistol/
asmar@asmarHPElite:~/test/pistol/cmd/pistol$ go build main.go 
go: downloading github.com/galdor/go-cmdline v1.1.0
go: downloading github.com/adrg/xdg v0.0.0-20190319220657-88e5137d2444
go: downloading github.com/sirupsen/logrus v1.4.2
go: downloading github.com/alecthomas/chroma v0.6.3
go: downloading github.com/mholt/archiver v0.0.0-20190623220050-33320f6f7306
go: downloading github.com/dustin/go-humanize v1.0.0
go: extracting github.com/sirupsen/logrus v1.4.2
go: downloading golang.org/x/sys v0.0.0-20190527104216-9cd6430ef91e
go: extracting github.com/dustin/go-humanize v1.0.0
go: extracting github.com/galdor/go-cmdline v1.1.0
go: extracting github.com/adrg/xdg v0.0.0-20190319220657-88e5137d2444
go: extracting github.com/mholt/archiver v0.0.0-20190623220050-33320f6f7306
go: downloading github.com/klauspost/pgzip v1.2.1
go: downloading github.com/pierrec/lz4 v2.0.5+incompatible
go: downloading github.com/klauspost/compress v1.7.1
go: downloading github.com/andybalholm/brotli v0.0.0-20190621154722-5f990b63d2d6
go: extracting github.com/alecthomas/chroma v0.6.3
go: extracting github.com/andybalholm/brotli v0.0.0-20190621154722-5f990b63d2d6
go: downloading github.com/golang/gddo v0.0.0-20190419222130-af0f2af80721
go: extracting github.com/golang/gddo v0.0.0-20190419222130-af0f2af80721
go: extracting github.com/pierrec/lz4 v2.0.5+incompatible
go: extracting github.com/klauspost/pgzip v1.2.1
go: extracting golang.org/x/sys v0.0.0-20190527104216-9cd6430ef91e
go: extracting github.com/klauspost/compress v1.7.1
go: downloading github.com/klauspost/cpuid v1.2.0
go: extracting github.com/klauspost/cpuid v1.2.0
go: finding github.com/adrg/xdg v0.0.0-20190319220657-88e5137d2444
go: finding github.com/alecthomas/chroma v0.6.3
go: finding github.com/dlclark/regexp2 v1.1.6
go: finding github.com/dustin/go-humanize v1.0.0
go: finding github.com/mholt/archiver v0.0.0-20190623220050-33320f6f7306
go: finding github.com/andybalholm/brotli v0.0.0-20190621154722-5f990b63d2d6
go: finding github.com/golang/gddo v0.0.0-20190419222130-af0f2af80721
go: finding github.com/klauspost/compress v1.7.1
go: finding github.com/klauspost/pgzip v1.2.1
go: finding github.com/klauspost/cpuid v1.2.0
go: finding github.com/pierrec/lz4 v2.0.5+incompatible
go: finding github.com/sirupsen/logrus v1.4.2
go: finding golang.org/x/sys v0.0.0-20190527104216-9cd6430ef91e
go: finding github.com/galdor/go-cmdline v1.1.0
asmar@asmarHPElite:~/test/pistol/cmd/pistol$ ./main -V
2019-12-12
asmar@asmarHPElite:~/test/pistol/cmd/pistol$ strace ./main ~/Downloads/table_rounding_problem.pdf 2>&1 | grep conf
newfstatat(AT_FDCWD, "/home/asmar/.config/pistol/pistol.conf", 0xc000086fa8, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/etc/xdg/xdg-mate/pistol/pistol.conf", 0xc000087078, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/etc/xdg/pistol/pistol.conf", 0xc000087148, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/home/asmar/.config/pistol.conf", 0xc000087218, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/etc/xdg/xdg-mate/pistol.conf", 0xc0000872e8, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/etc/xdg/pistol.conf", 0xc000087ca8, 0) = -1 ENOENT (No such file or directory)
```

**Comment by doronbehar** [comment]
Haha :sweat_smile: I forgot I'm using tags in this project. It's insane how much I needed to ask from you in order to realize this - and to realize that go get uses git tags to install "stable" versions of programs. Sorry about that!

I've tagged a new version - v0.0.3 and the verbosity flag reports that. Try `go get` now and tell me if it actually got updated and if it reads the correct config file.

**Comment by asmarcz** [comment]
No worries, I can relate. :D

The issue is now resolved.
```
asmar@asmarHPElite:~$ strace pistol ~/Downloads/table_rounding_problem.pdf 2>&1 | grep conf
newfstatat(AT_FDCWD, "/home/asmar/.config/pistol/pistol.conf", 0xc0004a93b8, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/etc/xdg/xdg-mate/pistol/pistol.conf", 0xc0004a9488, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/etc/xdg/pistol/pistol.conf", 0xc0004a9558, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/home/asmar/.config/pistol.conf", 0xc0004a96f8, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/etc/xdg/xdg-mate/pistol.conf", 0xc0004a97c8, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/etc/xdg/pistol.conf", 0xc0004a9898, 0) = -1 ENOENT (No such file or directory)
```
