### ISSUE TITLE
cleaner

### ISSUE THREAD

**Issue by lucas-mior** [doronbehar/pistol#79]
hello there.

`lf` has a `cleaner` options for previews, which is meant to be used after using `ueberzug` to display an image.
It will clear the screen when the user selects the next file so that the terminal can show up whatever next preview.

However, the problem with this approach is that everytime an image comes after the other, the cleaner will be unnecessarly called,
since all image previews shall return an error (which is a signal to lf to call the cleaner). This causes an annoying flickering between images, as noted in [this issue](https://github.com/gokcehan/lf/issues/626). `Ueberzug` replaces one image for the other very smoothly when the cleaner isn't executed.

In the aforementioned issue, the user suggests to allow control over the cleaner, but I think the better solution is for the preview program to clean the screen (if necessary). Maybe `pistol` could have an `cleaner` option, like lf, but also another option which sets which file types require that the previous one is cleared. The advantage is that other programs using `pistol`, like `fzf`, don't require to deal with this issue. The solution is within the previewer.

I could write a PR if it is possible to be accepted.
Cheers!

**Comment by doronbehar** [comment]
So you suggest to make `pistol` have a `--clean` option that will print (e.g?) empty lines of text in the amount of the number of lines in the text file it gets as the main argument?

What did you think to make `pistol` do when it gets a path to an image file?

**Comment by lucas-mior** [comment]
One approach is to have (let's say in `pistol.conf`) a `--clean` flag in the file type that needs cleaning before previewing them.
Basically to me that would mean everyfile that doesn't use `ueberzug`.

The cleaner is meant to be configureable (like in `lf`).

However, as I think about it, I think it might be a bit wrong to do it in `pistol`,
because the cleaner will be executed even when the previous file didn't use `ueberzug` at all.
(`pistol`, unlike `lf`, can't possibly know which file that was.

**Comment by doronbehar** [comment]
I'm sorry but I don't use ueberzug and I can't follow all the details.. It'd have been nice to see a screencast if that's possible. Intuitively, it seems as if `ueberzug` should be the program that would `clean` something if it's the one that made things dirty.

**Comment by lucas-mior** [comment]
It's been solved in `lf`.
