### ISSUE TITLE
how to use Uberzug to preview image?

### ISSUE THREAD

**Issue by niksingh710** [doronbehar/pistol#83]
[Uerberzug](https://github.com/seebye/ueberzug) 
How can i use this to have image previewed and pdf previewed?

**Comment by doronbehar** [comment]
It's a good question. I'm not sure I'd be interested in supporting this feature officially, if it comes out too complicated. Personally, I don't feel the need for this feature, so I won't be able to help you. See also the discussion in #2 .

**Comment by niksingh710** [comment]
@doronbehar 

[ueberzugpp](https://github.com/jstkdng/ueberzugpp)

Unable to figure out how to get this integrated in pistol.
if you figure out any way or someone does please share.

**Comment by doronbehar** [comment]
Closing in favor of #2.
